#-#-#-#-#-#-#-#-#-#-#-#-#-#
# $Id: Makefile,v 1.5 2006/02/28 20:57:26 mmr Exp $
# <mmr@b1n.org> 2004/02
#

# Prog
PROG=	hanoi
SRCS=	hanoi.c
OBJS=	hanoi.o

# Apps
CC=		gcc


# Flags
CFLAGS=
LDFLAGS=-framework OpenGL -framework GLUT

all: $(PROG)

$(SRCS):
	$(GET) $@

clean:
	-rm -f *.o *.core $(PROG)
