#-#-#-#-#-#-#-#-#-#-#-#-#-#
# $Id: Makefile,v 1.2 2006/01/12 22:32:39 mmr Exp $
# <mmr@b1n.org> 2004/02
#

# Prog
PROG=	hanoi.exe
SRC=	hanoi.c

# Apps
CC=		gcc


# Flags
LDFLAGS=-lglut32 -lglu32 -lopengl32 -mwindows

all:
	$(CC) -o $(PROG) $(SRC) $(LDFLAGS)
